apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: chimadocker2023/post:latest
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: django-srv
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - name: django
      port: 8000
      targetPort: 8000

