apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: chimadocker2023/react:0.0.1
        # imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: react-srv
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - name: react
      port: 3000
      targetPort: 3000
